development:
  adapter: postgresql
  encoding: unicode
  database: wikiufc
  username: wikiufc
  password: wikiufc

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/wiki.sqlite3
